name: CI

on:
  push:
    branches: [ master, feature/unit-test ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Build test Docker image
      run: |
        docker build -f Dockerfile.test -t repo-cleaner-test .
        
    - name: Run tests in Docker
      run: |
        docker run --rm -v ${{ github.workspace }}/coverage:/app/coverage \
        repo-cleaner-test
        
    - name: Build production Docker image
      run: |
        docker build -t repo-cleaner-prod .
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          coverage/
        retention-days: 30